config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :users do
      member do
        get :avalara_information
      end
    end
    resource :avatax_settings do
      get :ping_my_service, :get_file_txt_tax_svc, :get_file_post_order_to_avalara, :get_file_avalara_order, :erase_data
    end
    resources :avalara_entity_use_codes do

    end
  end
end

app/views/spree/admin/users/avalara_information.html.erb
<% content_for :page_title do %>
<%= link_to "#{Spree.t(:editing_user)} #{@user.email}", edit_admin_user_url(@user) %>
<% end %>

<%= render :partial => 'spree/admin/users/sidebar', :locals => { :current => :account } %>
<%= render :partial => 'spree/admin/users/user_page_actions' %>

<fieldset data-hook="admin_user_edit_general_settings" class="alpha twelve columns">
  <legend><%= Spree.t(:general_settings) %></legend>

  <div data-hook="admin_user_edit_form_header">
    <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user } %>
  </div>

  <div data-hook="admin_user_edit_form">
    <%= form_for [:admin, @user], as: :user, url: admin_user_url(@user), method: :put do |f| %>
    <div class="alpha six columns">
      <div class="field">
        <label>Customer Code</label>
        <input type="text" class="fullwidth" placeholder="<%= @user.id %>", readonly>
      </div>
    </div>
    <div class="omega six columns">
      <%= f.field_container :avalara_entity_use_code_id do %>
      <%= label_tag :avalara_entity_use_code_id, t(:avalara_entity_use_code) %><br />
      <%= hidden_field_tag 'user[avalara_entity_use_code_id]', f.object.avalara_entity_use_code_id , :class => "use_code_picker fullwidth" %>
      <% end %>
    </div>
    <div class="omega six columns">
      <%= f.field_container :exemption_number do %>
      <%= f.label :exemption_number, Spree.t(:exemption_number) %>
      <%= f.text_field :exemption_number, :class => 'fullwidth' %>
      <% end %>
    </div>
    <br><br><br>
    <div class="alpha fullwidth" data-hook="admin_user_edit_form_button">
      <%= render :partial => 'spree/admin/shared/edit_resource_links', :locals => { :collection_url => admin_users_url } %>
    </div>
  </div>
  <% end %>
</fieldset>