config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :users do
      member do
        get :avalara_information
      end
    end
    resource :avatax_settings do
      get :ping_my_service, :get_file_txt_tax_svc, :get_file_post_order_to_avalara, :get_file_avalara_order, :erase_data
    end
    resources :avalara_entity_use_codes do

    end
  end
end

app/controllers/spree/admin/avatax_settings_controller.rb
module Spree
  module Admin
    class AvataxSettingsController < Spree::Admin::BaseController

      respond_to :html

      def show
      end

      def get_file_txt_tax_svc
        send_file "#{Rails.root}/log/tax_svc.log"
      end

      def get_file_post_order_to_avalara
        send_file "#{Rails.root}/log/post_order_to_avalara.log"
      end

      def get_file_avalara_order
        send_file "#{Rails.root}/log/avalara_order.log"
      end

      def erase_data
        File.open(params['path'], 'w') {}
      end

      def ping_my_service
        mytax = TaxSvc.new
        pingResult = mytax.ping
        if pingResult['ResultCode'] == 'Success'
          flash[:success] = 'Ping Successful'

        else
          flash[:error] = 'Ping Error'
        end

        respond_to do |format|
          format.js
        end
      end

      def update
        origin = params[:address]
        taxpref = params[:settings]

        Spree::Config.avatax_origin = {
          :Address1 =>  origin[:avatax_address1],
          :Address2 => origin[:avatax_address2],
          :City => origin[:avatax_city],
          :Region => origin[:avatax_region],
          :Zip5 => origin[:avatax_zip5],
          :Zip4 => origin[:avatax_zip4],
          :Country => origin[:avatax_country]
        }.to_json

        Spree::Config.avatax_api_username = taxpref[:avatax_api_username]
        Spree::Config.avatax_api_password = taxpref[:avatax_api_password]
        Spree::Config.avatax_endpoint = taxpref[:avatax_endpoint]
        Spree::Config.avatax_account = taxpref[:avatax_account]
        Spree::Config.avatax_license_key = taxpref[:avatax_license_key]
        Spree::Config.avatax_iseligible = taxpref[:avatax_iseligible]
        Spree::Config.avatax_log = taxpref[:avatax_log]
        Spree::Config.avatax_address_validation = taxpref[:avatax_address_validation]
        Spree::Config.avatax_address_validation_enabled_countries = taxpref[:avatax_address_validation_enabled_countries]
        Spree::Config.avatax_tax_calculation = taxpref[:avatax_tax_calculation]
        Spree::Config.avatax_document_commit = taxpref[:avatax_document_commit]
        Spree::Config.avatax_company_code =taxpref[:avatax_company_code]

        respond_to do |format|
          format.html {
            redirect_to admin_avatax_settings_path
          }
        end
      end
    end
  end
end

app/views/spree/admin/avatax_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>
<% origin = JSON.parse(Spree::Config.avatax_origin) || {} %>
<h1><%= t('avatax_settings') %></h1>

<%= form_tag(admin_avatax_settings_path, :method => :put, :id => :avatax_settings_form) do %>

<div class="yui-g">
  <div class="yui-u first">
    <fieldset>
      <legend><%= t('avatax_api_login_and_key') %></legend>
      <p>
        <label><%= t('avatax_company_code') %></label><br />
        <%= text_field_tag('settings[avatax_company_code]', Spree::Config.avatax_company_code, :maxlength => 256, :class => 'avatax') %>
      </p>

      <p>
        <label><%= t('avatax_account') %></label><br />
        <%= text_field_tag('settings[avatax_account]', Spree::Config.avatax_account, :maxlength => 256, :class => 'avatax') %>
      </p>
      <p>
        <label><%= t('avatax_license_key') %></label><br />
        <%= text_field_tag('settings[avatax_license_key]', Spree::Config.avatax_license_key, :maxlength => 256, :class => 'avatax') %>
      </p>
    </fieldset>

    <fieldset>
      <legend><%= t('avatax_endpoint_urls') %></legend>
      <p>
        <label><%= t('avatax_endpoint') %></label><br />
        <%= text_field_tag('settings[avatax_endpoint]', Spree::Config.avatax_endpoint, :size => 46, :maxlength => 256, :class => 'avatax') %>
      </p>
      <p>
        <label><%= t('avatax_servicepath_tax') %></label><br />
        <input type="text" placeholder="<%= AVATAX_SERVICEPATH_TAX %>", readonly>
      </p>
      <p>
        <label><%= t('avatax_servicepath_address') %></label><br />
        <input type="text" placeholder="<%= AVATAX_SERVICEPATH_ADDRESS %>", readonly>
      </p>
      <p>
        <label><%= t('avatax_client_version') %></label><br />
        <input type="text" placeholder="<%= AVATAX_CLIENT_VERSION %>", readonly>
      </p>
    </fieldset>

    <fieldset>
      <legend><%= t('eligible') %></legend>
      <p>
        <label><%= t('enable_avatax') %></label><br />
        <%= check_box_tag('settings[avatax_iseligible]','yes' , Spree::Config.avatax_iseligible, :class => 'avatax') %>
      </p>
    </fieldset>

    <fieldset>
      <legend><%= t('avatax_log') %></legend>
      <p>
        <label><%= t('enable_avatax_logging') %></label><br />
        <%= check_box_tag('settings[avatax_log]','yes' , Spree::Config.avatax_log, :class => 'avatax') %>
      </p>
    </fieldset>

    <fieldset>
      <legend><%= t('avatax_address_validation') %></legend>
      <p>
        <label><%= t('enable_avatax_address_validation') %></label><br />
        <%= check_box_tag('settings[avatax_address_validation]','yes' , Spree::Config.avatax_address_validation, :class => 'avatax') %>
      </p>
    </fieldset>
      <fieldset>
      <legend><%= t('avatax_address_validation_enabled_countries') %></legend>
      <p>
        <% current_countries = Spree::Country.where(name: Spree::Config.avatax_address_validation_enabled_countries) %>
        <label><%= t('enable_avatax_address_validation_for_these_countries') %></label><br />
        <%= select_tag('settings[avatax_address_validation_enabled_countries]', options_from_collection_for_select(Spree::Country.all, "name", "name", selected: current_countries), multiple: true, class: "select2 fullwidth") %>
      </p>
    </fieldset>
    <fieldset>
      <legend><%= t('avatax_tax_calculation') %></legend>
      <p>
        <label><%= t('enable_avatax_tax_calculation') %></label><br />
        <%= check_box_tag('settings[avatax_tax_calculation]','yes' , Spree::Config.avatax_tax_calculation, :class => 'avatax') %>
      </p>
    </fieldset>

        <fieldset>
      <legend><%= t('avatax_document_committing') %></legend>
      <p>
        <label><%= t('enable_avatax_document_committing') %></label><br />
        <%= check_box_tag('settings[avatax_document_commit]','yes' , Spree::Config.avatax_tax_calculation, :class => 'avatax') %>
      </p>
    </fieldset>

    <fieldset>
      <legend><%= t('business_address') %></legend>
      <p>
        <label><%= Spree.t('address1') %></label><br />
        <%= text_field_tag('address[avatax_address1]', origin["Address1"], :size => 46, :maxlength => 256, :class => 'avatax') %>
      </p>
      <p>
        <label><%= Spree.t('address2') %></label><br />
        <%= text_field_tag('address[avatax_address2]', origin["Address2"], :size => 46, :maxlength => 256, :class => 'avatax') %>
      </p>
      <p>
        <label><%= Spree.t('city') %></label><br />
        <%= text_field_tag('address[avatax_city]', origin["City"], :size => 46, :maxlength => 256, :class => 'avatax') %>
      </p>
      <p>
        <label><%= Spree.t('state') %></label><br />
        <%= text_field_tag('address[avatax_region]', origin["Region"], :size => 46, :maxlength => 256, :class => 'avatax') %>
      </p>
      <p>
        <label><%= Spree.t('zipcode') %></label><br />
        <%= text_field_tag('address[avatax_zip5]', origin["Zip5"], :size => 46, :maxlength => 256, :class => 'avatax') %>
      </p>
      <p>
        <label><%= t('zip_plus_4') %></label><br />
        <%= text_field_tag('address[avatax_zip4]', origin["Zip4"], :size => 46, :maxlength => 256, :class => 'avatax') %>
      </p>
      <p>
        <label><%= t('country_code') %></label><br />
        <%= text_field_tag('address[avatax_country]', origin["Country"], :size => 46, :maxlength => 256, :class => 'avatax') %>
      </p>

    </fieldset>
    <fieldset>
    <legend><%= t('log_files') %></legend>
    <p>Log files are located in the log directory of your spree website.</p>
    <table>
    <tr>
   <td>
    <table>
      <tr>
        <td>Tax Service calls - tax_svc.log</td>
        <td><%= link_to("Download", {controller: :avatax_settings, action: :get_file_txt_tax_svc}) %>
        </td>
        <td>
          <%= link_to("Clear Data", {controller: :avatax_settings, action: :erase_data, remote: true, path: "log/tax_svc.log"}) %>
        </td>
      </tr>
      <tr>
        <td>Avalara Function calls -  post_order_to_avalara.log</td>
        <td><%= link_to("Download", {controller: :avatax_settings, action: :get_file_post_order_to_avalara}) %>
        </td>
        <td>
          <%= link_to("Clear Data", {controller: :avatax_settings, action: :erase_data, remote: true, path: "log/post_order_to_avalara.log"}) %>
        </td>
      </tr>
      <tr>
        <td>Spree Order Item integration calls - avalara_order.log</td>
        <td><%= link_to("Download", {controller: :avatax_settings, action: :get_file_avalara_order}) %>
        </td>
        <td>
          <%= link_to("Clear Data", {controller: :avatax_settings, action: :erase_data, remote: true, path: "log/avalara_order.log"}) %>
        </td>
      </tr>
    </table>
  </td>
</tr>
</table>
</fieldset>
  </div>
</div>

<p class="form-buttons"><%= button t('save_preferences') %></p>

<% end %>

app/views/spree/admin/avatax_settings/ping_my_service.js.erb
<% success = flash.discard(:success)
if success %>
show_flash('success', "<%= success %>")
<% end %>
<% error = flash.discard(:error)
if error %>
show_flash('error', "<%= error %>")
<% end %>

app/views/spree/admin/avatax_settings/show.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>
<% origin = JSON.parse(Spree::Config.avatax_origin) || {} %>
<h1><%= "Avalara Settings" %></h1>

<table>
  <tr>
    <th scope="row"><%= t("avatax_company_code") %>:</th>
    <td><%= Spree::Config.avatax_company_code %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("avatax_license_key") %>:</th>
    <td><%= Spree::Config.avatax_license_key %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("avatax_account") %>:</th>
    <td><%= Spree::Config.avatax_account %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("avatax_endpoint") %>:</th>
    <td><%= Spree::Config.avatax_endpoint %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("avatax_servicepath_tax") %>:</th>
    <td><%= AVATAX_SERVICEPATH_TAX %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("avatax_servicepath_address") %>:</th>
    <td><%= AVATAX_SERVICEPATH_ADDRESS %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("enable_avatax") %>:</th>
    <td><%= Spree::Config.avatax_iseligible %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("enable_avatax_logging") %>:</th>
    <td><%= Spree::Config.avatax_log %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("enable_avatax_address_validation") %>:</th>
    <td><%= Spree::Config.avatax_address_validation %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("avatax_address_validation_enabled_countries") %>:</th>
    <% address_validated_countries = Spree::Config.avatax_address_validation_enabled_countries %>
    <td>
      <% unless address_validated_countries.nil? %>
      <ul style="list-style: inside;">
        <% address_validated_countries.each do |country| %>
        <li><%= Spree::Country.find_by_name(country) %></li>
        <% end %>
      </ul>
      <% end %>
    </td>
  </tr>
  <tr>
    <th scope="row"><%= t("enable_avatax_tax_calculation") %>:</th>
    <td><%= Spree::Config.avatax_tax_calculation %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("enable_avatax_document_committing") %>:</th>
    <td><%= Spree::Config.avatax_document_commit %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("client_version") %>:</th>
    <td><%= AVATAX_CLIENT_VERSION %></td>
  </tr>

  <tr>
    <th scope="row"><%= t("business_address") %>:</th>

    <td><table>
      <tr><td><%= Spree.t("address1") %>: <%= origin["Address1"]  %> </td></tr>
      <tr><td><%= Spree.t("address2") %>: <%= origin["Address2"]  %></td></tr>
      <tr><td><%= Spree.t("city") %>: <%= origin["City"]  %></td></tr>
      <tr><td><%= Spree.t("state") %>: <%= origin["Region"]  %></td></tr>
      <tr><td><%= Spree.t("zipcode") %>: <%= origin["Zip5"]  %></td></tr>
      <tr><td><%= t("zip_plus_4") %>: <%= origin["Zip4"] %></td></tr>
      <tr><td><%= t("country_code") %>: <%= origin["Country"] %></td></tr>
    </table></td>
  </tr>
  <tr>
    <th>Connection Status</th>
    <td>
      <%= link_to({:controller => :avatax_settings, :action => :ping_my_service, :remote => true }, {:class => 'btn btn-small'}) do %>
      <button>Test Connection</button> <% end %>
    </td>

  </tr>



  <tr>
   <th>View Log Files</th>
   <td>
    Log files are located in the log directory of your spree website.
    <table>
      <tr>
        <td>Tax Service calls - tax_svc.log</td>
        <td><%= link_to("Download", {controller: :avatax_settings, action: :get_file_txt_tax_svc}) %>
        </td>
      </tr>
      <tr>
        <td>Avalara Function calls -  post_order_to_avalara.log</td>
        <td><%= link_to("Download", {controller: :avatax_settings, action: :get_file_post_order_to_avalara}) %>
        </td>
      </tr>
      <tr>
        <td>Spree Order Item integration calls - avalara_order.log</td>
        <td><%= link_to("Download", {controller: :avatax_settings, action: :get_file_avalara_order}) %>
        </td>
      </tr>
    </table>
  </td>
</tr>
</table>

<p><%= link_to_with_icon 'edit', Spree.t("edit"), edit_admin_avatax_settings_path %></p>

app/views/spree/admin/avatax_settings/validate_address.js.erb
<% success = flash.discard(:success)
if success %>
show_flash('success', "<%= success %>")
<% end %>
<% error = flash.discard(:error)
if error %>
show_flash('error', "<%= error %>")
<% end %>